sonar.projectKey=oficina-api
sonar.projectName=Oficina API
sonar.projectVersion=1.0
sonar.host.url=http://localhost:9000
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src,test
sonar.test.inclusions=**/*.spec.ts,**/*.e2e-spec.ts
sonar.exclusions=**/*.spec.ts,**/*.e2e-spec.ts,**/*.module.ts,**/*.dto.ts,**/node_modules/**,**/dist/**,**/coverage/**,prisma/migrations/**,bruno/**

sonar.typescript.lcov.reportPaths=coverage/lcov.info
