apiVersion: v1
kind: ConfigMap
metadata:
  name: oficina-config
  labels:
    app: oficina-api
data:
  PORT: "3000"
  JWT_EXPIRES_IN: "8h"
  SMTP_HOST: "mailhog"        # em produção: host SMTP real (sobrescrever)
  SMTP_PORT: "1025"
  SMTP_FROM: "oficina@localhost"
