apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: oficina-api-hpa
  labels:
    app: oficina-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: oficina-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          # equivalente ao `targetCPUUtilizationPercentage: 70` do autoscaling/v1 das aulas
          type: Utilization
          averageUtilization: 70
