vars:
  url: http://localhost:3000
  token: ""
  clienteId: ""
  usuarioId: ""
  veiculoId: ""
  servicoId: ""
  insumoId: ""
  osId: ""
  osNumero: ""
  itemServicoId: ""
  itemInsumoId: ""
  documentoCliente: ""
  registroCompraId: ""
